[build]
base = "./"
command = "bun run build"
publish = "./dist"

#   --------------------   URL REDIRECTS   --------------------
[[redirects]]
force = true
from = "https://lario-f09798.netlify.app/"
status = 301
to = "https://lariocpt.biz"

#   --------------------   RESPONSE HEADERS   --------------------
# [[plugins]]
#   package = "@netlify/plugin-csp-nonce"
#   [plugins.inputs]
#     reportOnly = false

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = '''
    frame-ancestors 'self',
    object-src 'none',
    connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com,
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com,
    img-src 'self' https://*.analytics.google.com https://*.google-analytics.com https://*.googletagmanager.com https://images.ctfassets.net,
		require-trusted-types-for 'script'
    '''
Cross-Origin-Opener-Policy = "same-origin"
Referrer-Policy = "no-referrer"
Strict-Transport-Security = '''
    max-age=63072000,
    includeSubDomains,
    preload
    '''
X-Content-Type-Options = "nosniff"
X-DNS-Prefetch-Control = "on"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = '''
    1,
    mode=block'''

[[headers]]
for = "*.(css|js|ts|webp|jpg|jpeg|png|ttf|otf|woff|woff2|eot)"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*/"
[headers.values]
Cache-control = '''
    public,
    max-age=300,
    must-revalidate
    '''
