[build]
  base = "./"
  publish = "./dist"
  command = "corepack enable && yarn build"
  cssMinify = true
  assetsDir = "public"
  cssCodeSplit = true
  sourcemap = true
  minify = true
  hashfiles = true


#   --------------------   URL REDIRECTS   --------------------
[[redirects]]
  from = "https://lario-f09798.netlify.app/"
  to = "https://lariocpt.biz"
  status = 301
  force = true


#   --------------------   RESPONSE HEADERS   --------------------
[[headers]]
  for = "/*"
  [headers.values]
    X-DNS-Prefetch-Control = "on"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-XSS-Protection = '''
    1,
    mode=block'''
    Strict-Transport-Security = '''
    max-age=63072000,
    includeSubDomains,
    preload
    '''
    Content-Security-Policy = '''
    frame-ancestors 'self' https://fonts.googleapis.com https://fonts.gstatic.com,
    object-src 'none',
    script-src https://*.googletagmanager.com 'self',
    img-src 'self' https://*.google-analytics.com https://*.googletagmanager.com,
    connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com
    '''

[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = '''
    no-cache,
    no-store,
    must-revalidate'''

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000
    '''

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000
    '''

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000
    '''

[[headers]]
  for = "*.ts"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000
    '''



#   --------------------   PLUGINS/INTEGRATIONS   --------------------
# [[plugins]]
#   package = "netlify-plugin-hugo-cache-resources"
# 	[plugins.inputs]
#     baseURL = "."
#     debug = true
#     srcdir = "src"

# [[plugins]]
#   package = "netlify-plugin-submit-sitemap"
# 	[plugins.inputs]
#     baseUrl = "https://lariocpt.dev"
#     sitemapPath = "/sitemap.xml"
#     ignorePeriod = 0
#     providers = [
#       "google",
#       "yandex"
#     ]
