[build]
base = "./"
command = "bun run build"
cssCodeSplit = true
cssMinify = true
hashfiles = true
minify = true
publish = "./dist"
sourcemap = true

#   --------------------   URL REDIRECTS   --------------------
[[redirects]]
force = true
from = "https://lario-f09798.netlify.app/"
status = 301
to = "https://lariocpt.biz"

#   --------------------   RESPONSE HEADERS   --------------------
# [[plugins]]
#   package = "@netlify/plugin-csp-nonce"
#   [plugins.inputs]
#     reportOnly = false

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = '''
    frame-ancestors 'self' https://fonts.googleapis.com https://fonts.gstatic.com,
    object-src 'none',
    connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com
    '''
Referrer-Policy = "no-referrer"
Strict-Transport-Security = '''
    max-age=63072000,
    includeSubDomains,
    preload
    '''
X-Content-Type-Options = "nosniff"
X-DNS-Prefetch-Control = "on"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = '''
    1,
    mode=block'''
# img-src 'self' https://*.google-analytics.com https://*.googletagmanager.com https://images.ctfassets.net/**/*,

[[headers]]
for = "*.html"
[headers.values]
Cache-control = '''
    public,
    max-age=300,
    must-revalidate
    '''

[[headers]]
for = "*.(css|js|ts|webp|jpg|jpeg|png|ttf|otf|woff|woff2|eot)"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

# [[headers]]
# for = "*.css"
# [headers.values]
# Cache-control = '''
#     public,
#     max-age=31536000,
#     immutable
#     '''

# [[headers]]
# for = "*.js"
# [headers.values]
# Cache-control = '''
#     public,
#     max-age=31536000,
#     immutable
#     '''

# [[headers]]
# for = "*.ts"
# [headers.values]
# Cache-control = '''
#     public,
#     max-age=31536000,
#     immutable
#     '''

[[headers]]
for = "*.webp"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.jpg"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.jpeg"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.png"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.ttf"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.otf"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.woff"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.woff2"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "*.eot"
[headers.values]
Cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

#   --------------------   PLUGINS/INTEGRATIONS   --------------------
# [[plugins]]
#   package = "netlify-plugin-hugo-cache-resources"
# 	[plugins.inputs]
#     baseURL = "."
#     debug = true
#     srcdir = "src"

# [[plugins]]
#   package = "netlify-plugin-submit-sitemap"
# 	[plugins.inputs]
#     baseUrl = "https://lariocpt.dev"
#     sitemapPath = "/sitemap.xml"
#     ignorePeriod = 0
#     providers = [
#       "google",
#       "yandex"
#     ]
